### ISSUE TITLE
support url scheme

### ISSUE THREAD

**Issue by steve21124** [Jasonette/JASONETTE-iOS#10]
support url scheme like `appname://url/https://jasonbase.com/things/fen.json`, and it opens that particular url

**Comment by gliechtenstein** [comment]
I pushed a fix overnight. Here's how it works:

The url scheme takes the following form:

`appname://href?url=https://jasonbase.com/things/fen.json&transition=modal&view=jason`

Basically it translates the arguments into an [href](https://jasonette.github.io/documentation/href/) object and acts accordingly. So for example if you just wanted to do a push transition to a url, you could just leave out 'transition' like this:

`appname://href?url=https://jasonbase.com/things/fen.json`

Need to test a bit and then will merge to master. If anyone wants to try this out, please clone from develop branch and try it.

p.s. 
You can find the url scheme prefix when you run `Setup`. (Or you can change it to you liking by opening Info.plist and find URL scheme attribute)

![screen shot 2016-11-05 at 1 45 44 pm](https://cloud.githubusercontent.com/assets/16613330/20032308/2c97af48-a35e-11e6-981a-11c91a6fc608.png)

**Comment by steve21124** [comment]
thank you. super fast turn around

**Comment by mcken2ja** [comment]
Does this support the options and params feature in href?
