### ISSUE TITLE
Textfield and textarea issues

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#108]
This is a multipart issue:

**1. Padding in textfield component does not appear to work**

https://jasonbase.com/things/AXj.json

![simulator screen shot 4 jan 2017 10 40 34 pm](https://cloud.githubusercontent.com/assets/3887694/21642564/d594a372-d2ce-11e6-8bfa-a2d20fff1d29.png)

**2. Padding in the textarea component does not appear to work**

- Try changing the padding value for either issue above

**3. Inconsistency in 'corner radius' for textarea component**

If the value in a textarea is obtained from a cache item (e.g. `$cache.about`), then `corner_radius` does not appear to work. It only seems to work when the value of the textarea isn't a Jason object.

**Comment by drwasho** [comment]
With the third part of the issue, turns out that the corner radius rendered properly after closing and reopening the app.

**Comment by gliechtenstein** [comment]
Please check the latest develop branch, the padding should work. let me know if it works!

**Comment by drwasho** [comment]
Nice!

![simulator screen shot 5 jan 2017 12 20 56 am](https://cloud.githubusercontent.com/assets/3887694/21645235/f549a29a-d2dc-11e6-9849-ed0f6cd4a4ff.png)

Only thing I noticed was that it only worked with `padding` and not `padding_left`... but not sure whether that kind of control is necessary.

**Comment by gliechtenstein** [comment]
Yes, I started trying to implement padding_left, padding_top, et al, but realized this introduces a lot of hidden complexity. For now textareas and textfields only support `padding`.

Closing this for now since it works for `padding`. May revisit if we come across a critical case where `padding_left`, `padding_top` etc are very necessary.

**Comment by drwasho** [comment]
That's perfectly reasonable, thanks!
