### ISSUE TITLE
Shipping to App Store documentation.

### ISSUE THREAD

**Issue by IvRRimum** [Jasonette/JASONETTE-iOS#11]
From HN:
@blairanderson 1 hour ago [-]

I would recommend adding documentation for shipping to the App Store.
Even if it's as simple as "just build and submit".

**Comment by gliechtenstein** [comment]
I can't personally get to this anytime soon but I'm hoping someone could jump in and help.

I agree this is the "last mile" thing. Since everything else is so streamlined, if we can make this part super straightforward, even a grandma can make an app!

**Comment by gliechtenstein** [comment]
I just created an entry and added some notes and images https://jasonette.github.io/documentation/#submitting-to-the-app-store

I think this is good enough for now and will close. But feel free to reopen or update if anyone has improvement. Thanks!
