### ISSUE TITLE
Fix $audio

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-iOS#112]
For some reason $audio.play just goes into hibernation when the device goes into background.

It was definitely working before, I'm pretty sure this bug was introduced due to iOS10.

Will need to fix this

**Comment by ghost** [comment]
I found a fix, capabilities/background modes/audio

**Comment by gliechtenstein** [comment]
Aha! 
I swear I had turned this on, I don't know how it got lost along the way! I just went back and updated and re-pushed : https://github.com/Jasonette/JASONETTE-iOS/commit/0d0fe358609be83be4cf12da9484266e3f8cf926

Thanks for finding this out!
