### ISSUE TITLE
Request: pass variables from footer tabs

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#116]
If I hit a footer tab, I'd love to be able to pass on a variable I obtained in the parent view to the child view.

Something like this:

```
{
  "image": "https://maxcdn.icons8.com/iOS7/PNG/75/Business/shop-75.png",
  "style": {
    "height": "21"
  },
  "url": "https://jasonbase.com/things/123.json",
  "options": {
    "variable": "{{$cache.variable}}"
  }
}
```

**Comment by gliechtenstein** [comment]
Related https://github.com/Jasonette/JASONETTE-iOS/issues/22

**Comment by drwasho** [comment]
Closing this as @gliechtenstein added it to a branch some time ago and it is destined to be merged into dev/master soon.

**Comment by gliechtenstein** [comment]
Yes I confirm that this has been merged into develop branch.
