### ISSUE TITLE
REQUEST: Set label color for body.header

### ISSUE THREAD

**Issue by jet10000** [Jasonette/JASONETTE-iOS#117]
I set body.header background black, I want to set label color for body.header

**Comment by gliechtenstein** [comment]
Sorry about that, I don't know why it's not documented. Just added the attribute to the documentation https://github.com/Jasonette/documentation/commit/a7089d89aaae164a63531616b84c304942cc4d44

Basically you can use `body.header.style.color` to set the font color of the title. Please reopen if this doesn't work!
