### ISSUE TITLE
Footer tab selection post-transition of a view

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#118]
**Description**
Under circumstances where you are in a view, and the corresponded tab appears selected, it remains in this stage even after transitioning to a new view using the `replace` attribute.

**Code**
https://jasonbase.com/things/MMg.json (start here)
https://jasonbase.com/things/2Qo.json

**Comment by drwasho** [comment]
@gliechtenstein a more fundamental problem is that if you have a `$pull` action, the view will reload to the original view. I'll update the examples.

**Comment by gliechtenstein** [comment]
Should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/977fee2855c1e76d00550c890fd5b84b334c2f20

Please try and confirm, thanks!

**Comment by drwasho** [comment]
Will do

**Comment by drwasho** [comment]
Fixed
