### ISSUE TITLE
Map zoom is changed and pins are duplicated each time map is refreshed

### ISSUE THREAD

**Issue by jvelgos** [Jasonette/JASONETTE-iOS#119]
In the latest develop branch, when the map is refreshed (because the app is backgrounded and then brought back to the foreground or because the map is scrolled out of view and then back into view) the map zoom changes and it appears that the map pins are being duplicated.

To experience the issue, build an app using the develop branch and this config JSON:
https://jasonbase.com/things/Po6.json

I would suggest disallowing Location when asked so it defaults to the region where the map pins are (instead of your current location).

Once you've built the app, background and re-open the app. The map will zoom in (which it shouldn't) the first time you do this, and each successive time, the map pin shadows will get darker (I think this is  because the pins are being duplicated).

This issue doesn't occur when running the same JSON file mentioned above inside the version of the Jason app that's currently in the app store, so I believe it's a new issue.

Here's an animated GIF showing the behavior:

![map-pins](https://cloud.githubusercontent.com/assets/18070441/21989005/49bbf622-dbd7-11e6-8e4e-7b8ada6fcabc.gif)

**Comment by gliechtenstein** [comment]
This should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/81827a8162c369f00fb660d10a19fb0e38f7fd5f


Please try and let us know!

**Comment by jvelgos** [comment]
@gliechtenstein Thanks! It seems mostly fixed now. The pin shadows no longer get darker each time the map is refreshed and the map zoom no longer resets each time the map is refreshed, either.

That said, the pin shadows are now starting out darker than they used to, so it seems like there might still be two sets of them (they just don't continue to duplicate beyond that).

Also, the map zoom no longer resets each time the map is refreshed, which is good, but it's still not respecting the height and width I set for the map region (which it used to) so I can't change the initial zoom level.

**Comment by gliechtenstein** [comment]
@jvelgos I just figured out the problem with redundant pins and working on fixing it.

As for the zoom feature, can you try it again? Its working on mine. I tried with width/height from 50,50 to 100,100 to 1000,1000 and they all show up differently. (I'm using a copy of your json)

**Comment by gliechtenstein** [comment]
Just fixed the pin issue https://github.com/Jasonette/JASONETTE-iOS/commit/46782dab434d3ae88ebd53f238ce0bf76e0b0720

Please try the zoom and share if it works.

**Comment by gliechtenstein** [comment]
@jvelgos did this work?

**Comment by jvelgos** [comment]
@gliechtenstein The pins look correct, but it's still ignoring the zoom level I've set. Here's a comparison of the same JSON file loaded in the Jason app from the app store (correct zoom) and my Xcode project using the latest from Develop:

![initial-zoom](https://cloud.githubusercontent.com/assets/18070441/22066256/29efdba4-dd5a-11e6-9456-ddc91c875227.png)

**Comment by gliechtenstein** [comment]
@jvelgos could you try changing the region and see if it changes the zoom level at all?

Right now I'm looking at your https://jasonbase.com/things/Po6.json and it looks like the region is set to 50x50 (meters). Assuming that we're looking at the same JSON, I think the zoom level in your XCode project is the correct one (the Jason version is the wrong one)

Please let me know, thanks!

**Comment by jvelgos** [comment]
@gliechtenstein Ah, interesting. Changed it to 200x200 and it looks correct in the Xcode version now (although I had to delete and reinstall both apps, for some reason. they seemed to cache the region size or something). The Jason version is even more zoomed out, so I guess there's a bug in that one.

So anyway, looks like it's all set. Thanks so much!

**Comment by gliechtenstein** [comment]
@jvelgos yup, this bug fix was made after I submitted the latest version of Jason so the bug should still be there on Jason. Will push another update to the app store soon. Thanks for the report! 💯
