### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by appwiz** [Jasonette/JASONETTE-iOS#12]
Very cool project!

Could you add an explicit LICENSE file to the repository? I see that you've mentioned that the project is [MIT licensed at the end of the README](https://github.com/Jasonette/JASONETTE-iOS/blob/develop/README.md). Still would be helpful to include it as a separate explicit LICENSE file. One benefit is that [Github will detect the license and display it](https://help.github.com/articles/adding-a-license-to-a-repository/) at the top of the repository page.

Keep up the great work!

**Comment by gliechtenstein** [comment]
Thank you! Done! Resolved with https://github.com/Jasonette/JASONETTE-iOS/commit/b71ceaf53819047522dbcb2af86ea54c0457ad44
