### ISSUE TITLE
I want to programmatically generate JSON file

### ISSUE THREAD

**Issue by jet10000** [Jasonette/JASONETTE-iOS#125]
I want to programmatically generate JSON file, but Jason's template syntax conflict to already existing server-side template engine, for example, jinjia2.

http://jinja.pocoo.org/

**Comment by gliechtenstein** [comment]
You can escape characters http://jinja.pocoo.org/docs/2.9/templates/#escaping

Please try and let me know if that works, thanks!

**Comment by jet10000** [comment]
just test it , It's not work. I don't know why.

Maybe I will consider use html, and then convert html to json.

**Comment by jet10000** [comment]
`<head>
    <meta charset="UTF-8">
    <title>{% autoescape off %}{{ title }}{% endautoescape %}</title>
</head>
<body>
    <header>
        <div id="title" style="color: #000;">test</div>
        <menu></menu>
    </header>
    <footer></footer>
</body>
`

**Comment by jet10000** [comment]
`
<head>
    <meta charset="UTF-8">
    <title>{% autoescape off %}{{ title }}{% endautoescape %}</title>
</head>
<body>
    <header>
        <div id="title" style="color: #000;">test</div>
        <menu></menu>
    </header>
    <footer></footer>
</body>
`

**Comment by jet10000** [comment]
```
<head>
    <meta charset="UTF-8">
    <title>{% autoescape on %}{{ title }}{% endautoescape %}</title>
</head>
<body>
    <header>
        <div id="title" style="color: #000;">test</div>
        <menu></menu>
    </header>
    <footer></footer>
</body>

```
django template

**Comment by gliechtenstein** [comment]
Actually, i just looked at jinja and it's an HTML templating engine, it's for templating HTML. On Jasonette we are expecting JSON, so it's completely unrelated.

For Jasonette you should construct the JSON yourself. In case of rails there are some libraries that make it easier such as jBuilder and Rabl, and I'm sure there's a common way of doing things like that on python as well.

But even in the worst case you can just construct them manually using python. Hope this helps!
