### ISSUE TITLE
Request: In $util.share action, enable Save to Camera Roll option for single image shares in the Share Sheet

### ISSUE THREAD

**Issue by jeffreybetts** [Jasonette/JASONETTE-iOS#129]
When using _$util.share_ to share a single image, the share sheet displays. Currently the only default actions that is available are are only Copy and Save to iCloud Drive. It would be great if there was an option to enable the Save to Camera Roll option as well, so you can save an image directly to the local device's photo library.

**Comment by gliechtenstein** [comment]
Sorry for the delay! Turns out it was just a simple fix. Should have taken a look earlier! Should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/72b03d1a06522fae24259cd339c4520bb4cdd634

Let me know if it worked, and i'll close this

**Comment by jeffreybetts** [comment]
Thanks @gliechtenstein 
I just tested this in the latest Jason app and it works.
