### ISSUE TITLE
footer.input shouldn't update when $render happens

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-iOS#134]
Right now whenever the `$render` action is run while the `footer.input` is in focus, the `footer.input` disappears to the bottom.

This shouldn't happen. The footer.input should not be touched when `$render` happens.

**Comment by gliechtenstein** [comment]
Should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/803050e5d14b1e2ca6b0bb6a811d8993c001b882

If anyone can verify, please comment, and i'll close

**Comment by drwasho** [comment]
Verified!
