### ISSUE TITLE
BUGish?: $util.share doesn't send text to Facebook

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#139]
It shares the image, but not the text.

**Comment by gliechtenstein** [comment]
Just did some googling and looks like Facebook is intentionally blocking this behavior both on iOS and Android http://stackoverflow.com/questions/29881531/ios-8-3-and-later-facebook-share-text-not-inserted

Can't really do anything from the OS side so gonna have to close this for now.

One solution would be write a facebook share extension, using Facebook's own API.

Please feel free to re-open if you have a different suggestion.
