### ISSUE TITLE
$util.datepicker "ok" "cancel" buttons are overflowed by "tabs"

### ISSUE THREAD

**Issue by carstengrimm** [Jasonette/JASONETTE-iOS#154]
Bottom Tabs Menu overflows $util.datepicker so the selected date/time cannot be accepted because "ok" as well as "cancel" buttons are not visible as well as pushable.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/a661b584b56045ce3c7c19c6ae5c9051afe5c989

Try it out on develop branch and please reopen if it doesn't work!
