### ISSUE TITLE
Support For Alpha in Component Backgrounds

### ISSUE THREAD

**Issue by tomershvueli** [Jasonette/JASONETTE-iOS#16]
When adding a component, I'd like to be able to set the alpha of that component using the "background" key with a valid RGBA value. At the moment, if I set the 'A' value to anything besides 0, it will color it fully, without opacity.

**Comment by tomershvueli** [comment]
After digging into the code, I saw that I can add an 'opacity' value! Lovely!

**Comment by gliechtenstein** [comment]
you can also use RGBA colors https://jasonette.github.io/documentation/convention/#values :)
