### ISSUE TITLE
Bug? Space height/width < 1

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#163]
Simple View (one components of 0.5 height):

https://jasonbase.com/things/geje.json

Complex View (multiple components that show a gradient of height sizes from 0.5 - 4): 

https://jasonbase.com/things/YPaL.json

Height of < 1 seem to work fine on Android, and I can provide some screenshots if required.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/7697aa4dc7305c327498ef7d403294169613f1f9

Please confirm

**Comment by drwasho** [comment]
Boom!
