### ISSUE TITLE
Can't hide header

### ISSUE THREAD

**Issue by Armenm** [Jasonette/JASONETTE-iOS#166]
Hi there,
I want to hide header for my app. I couldn't find anything on that part in documentation.
Is that possible?

**Comment by gliechtenstein** [comment]
It's kind of tricky to allow this behavior AND support navigation (imagine transitioning from view A to view B and the view B doesn't have a header, the user would be stuck there with no way to come back to view A).

But one workaround is to make the header transparent by setting the header's style.background to `rgba(0,0,0,0)`. Hope this helps.
