### ISSUE TITLE
Potential bug: button image stretching

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#167]
Code: https://jasonbase.com/things/43k3.json

Problem: when the view loads, the button/image is stretched vertically when loaded initially (this part is important)... but if you reload the view, the image renders correctly.

**Comment by drwasho** [comment]
**Initial load:**

![img_0257 2](https://cloud.githubusercontent.com/assets/3887694/25110173/3e8d889c-2425-11e7-9d0b-9010c9dccb4c.PNG)

**Reload**

![img_0258](https://cloud.githubusercontent.com/assets/3887694/25110177/468fb8c6-2425-11e7-9c45-073fbcfe9373.PNG)

**Comment by gliechtenstein** [comment]
Should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/5e66f7c3d04f7726056324e188a981394725b46d please confirm

**Comment by drwasho** [comment]
Great work!
