### ISSUE TITLE
Potential Bug: item padding for a space component

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#169]
Apologies for the vague title:

https://jasonbase.com/things/BwZl.json

I have a vertical item, within that item I have a vertical set of components that have a padding left/right of 15. The only component is a space that is to act as a separator line.

The line shouldn't be drawn across the entire width of the view, but it is. There also appears to be a second line that is superimposed on that.

Very unusual and may be tied to other problems that have caused my app to crash using this type of component when I had `padding_top` and `padding_bottom` set to `0` (curiously the app didn't crash with one of these was omitted, but when both were included => crash... but this problem is beyond the scope of this issue).

**Comment by gliechtenstein** [comment]
The "superimposed" line is the border (of the item), so if you set the `border` to `none`, it goes away, like this: 

![img_1463](https://cloud.githubusercontent.com/assets/16613330/25364191/a03b5174-292e-11e7-8280-c9cbe2ca502d.PNG)


You can see that there are 15 pixel paddings to the left and right. Here's the code:


```
{
  "$jason": {
    "head": {
      "title": "Jasonette Template",
      "actions": {
        "$load": {
          "type": "$render"
        },
        "$pull": {
          "type": "$reload"
        }
      },
      "templates": {
        "body": {
          "style": {
            "border": "none"
          },
          "sections": [
            {
              "items": [
                {
                  "type": "vertical",
                  "style": {
                    "padding_top": "20",
                    "padding_bottom": "0",
                    "padding_left": "15",
                    "padding_right": "15",
                    "background": "#ffffff"
                  },
                  "components": [
                    {
                      "type": "space",
                      "style": {
                        "background": "#d3d3d3",
                        "height": "0.5"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

**Comment by drwasho** [comment]
If `padding_top` was omitted I found that the app crashed. Did you see that too?

Getting rid of the border did get rid of the superimposed line though, +1!

**Comment by drwasho** [comment]
@gliechtenstein I updated https://jasonbase.com/things/BwZl.json to omit `padding_top` to demo the crash.

**Comment by gliechtenstein** [comment]
I just tried the latest version of BwZl and it doesn't seem to crash. Can you delete and reinstall and try again?

**Comment by drwasho** [comment]
Yep this isn't a problem anymore.
