### ISSUE TITLE
$audio issue, causes app crash on iOS and Android 

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#184]
Reproduce with:

https://jasonbase.com/things/dmmb.json

**click the item**

iOS: crashes immediately 
```
    BBBadgeBarButtonItem *rightBarButton;
    if(!right_menu || [right_menu count] == 0){
        rightBarButton = nil;
    }
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x17403bd40' ***
```

Android, gets further, shows view, crashes when clicking the "play" button.

iOS latest, Android 7.0

Thanks

**Comment by gliechtenstein** [comment]
I took a look at the markup and there's a problem with the syntax you're using. According to the documentation http://docs.jasonette.com/document/#menu , a `menu` is an object which contains multiple items like `text`, `image`, `style`, `href`, `action`, etc. In your case you're setting:

```
          "header": {
            "title": {
              "type": "image", 
              "style": {
                "height": "27", 
                "width": "94"
              }, 
              "url": "https://kadist-ios.herokuapp.com/static/images/kadist-header.png?ver=1.33"
            }, 
            "menu": "{{$params.title}}"
          }
```

Here, `$params.title` is just a string, which is why it's crashing.

**Comment by ghost** [comment]
doh! thanks.

**Comment by ghost** [comment]
this was the iOS problem but on Android as soon as I click the play/pause button it plays, but I get a message saying the application "Jason has stopped" (or something similar).  This seems like a different issue, should I open a separate issue for that on the andorid githib?/

**Comment by gliechtenstein** [comment]
Yes please open an issue on the android repo with the replicable code. I think these are different issues

**Comment by ghost** [comment]
issue created: https://github.com/Jasonette/JASONETTE-Android/issues/99
