### ISSUE TITLE
Bug: Interrupting $require with actions

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#198]
**Description**

If you have initiated a require action, there are two problems that the user will encounter:

1. They cannot initiate trigger an action within the current view while the network request is being performed
2. If the user touches a tab footer, the next view will fail to load. 

**Code for testing**

https://jasonbase.com/things/dmpb.json (tab 1)
https://jasonbase.com/things/32lX.json (tab 2)

Also see additional comments in https://github.com/Jasonette/JASONETTE-iOS/issues/197

**Comment by gliechtenstein** [comment]
This should be fixed along with https://github.com/Jasonette/JASONETTE-iOS/issues/197#issuecomment-305237464

Please confirm.

**Comment by drwasho** [comment]
Confirmed, great job!
