### ISSUE TITLE
$network.request support for Content-Type: application/vnd.api+json

### ISSUE THREAD

**Issue by m-collins** [Jasonette/JASONETTE-iOS#234]
I am making a network request to an API that follows the following json api spec jsonapi.org

The request fails with the following error: NSLocalizedDescription=Request failed: unacceptable content-type: application/vnd.api+json}

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/34291829f888d160e619d119603bcce15ae01396
