### ISSUE TITLE
no longer seeing loading.json being rendered

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#248]
Used to work, but with latest develop build I'm not seeing the loading.json ever being show.

**Comment by gliechtenstein** [comment]
I think this has to do with the `file://` based loading. I just tried your http url and that one is showing the loading fine.

Could you share the project or the asset files so i can test and fix it?

**Comment by ghost** [comment]
that was the problem. closing. (my fault)
