### ISSUE TITLE
Is it possible to support CocoaPods?

### ISSUE THREAD

**Issue by ringfox** [Jasonette/JASONETTE-iOS#266]
It would be more convenient to integrate Jasonette. Thank you!

**Comment by maks** [comment]
Do you mean to have Jasonette available as a cocoapod to include within an app project?

**Comment by fernandopena** [comment]
Could this issue be opened again? It would be nice to have Jasonette available as a cocoapod dependency to include it on existing projects. I currently have an iOS App and would like to add Jasonette to remotely update just some views of the App.
