### ISSUE TITLE
$pull to $reload action weirdness

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#277]
Even slightly pulling down the view will trigger the $pull action.

Test: https://jasonbase.com/things/jXQ6

**Comment by gliechtenstein** [comment]
Please try testing with this branch https://github.com/Jasonette/JASONETTE-iOS/pull/278

Now using native UIRefreshControl.

**Comment by drwasho** [comment]
![0](http://i0.kym-cdn.com/entries/icons/original/000/022/900/704.jpg)

**Comment by gliechtenstein** [comment]
Resolved
