### ISSUE TITLE
UITextField doesn't slide up when keyboard appears on iOS 11

### ISSUE THREAD

**Issue by warrawan** [Jasonette/JASONETTE-iOS#280]
UITextField doesn't slide up when keyboard appears on iOS 11
<img src="https://user-images.githubusercontent.com/3924230/30765251-6d204d86-9ff7-11e7-88d0-92e9372cc4d4.gif" alt="simulator 23-09-2017" style="max-width:100%;">

https://www.jasonbase.com/things/MYXL 
Help me please

**Comment by gliechtenstein** [comment]
@warrawan i just tried to test it out but the link opens a different view..

**Comment by gliechtenstein** [comment]
I just went ahead and fixed this problem. https://github.com/Jasonette/JASONETTE-iOS/pull/281

Please try it out and let me know if that fixed it and I'll close the issue.

**Comment by gliechtenstein** [comment]
Well, can't really keep this hanging so gonna close this. Feel free to reopen if it's not fixed.
