### ISSUE TITLE
Modal weirdness if parent view has a tabbar

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#283]
Silhouette of the tabbar appears in a modal if you trigger it.

Parent view: https://jasonbase.com/things/E1l8
Modal view: https://jasonbase.com/things/zMeQ

**Comment by gliechtenstein** [comment]
Try this branch https://github.com/Jasonette/JASONETTE-iOS/pull/284

**Comment by gliechtenstein** [comment]
Confirmed fix, closing
