### ISSUE TITLE
The main template.body.header isn't getting colored

### ISSUE THREAD

**Issue by NikhilKodilkar** [Jasonette/JASONETTE-iOS#293]
The back button & the menu do take the color, but the actual header remains Black.

Here is the sample code:
https://www.jasonbase.com/things/wnYV

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/91b0c34eaee57479ba686e8687ce8af2599f28f4
