### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by Corstiaan84** [Jasonette/JASONETTE-iOS#295]
Hi there. I am considering Jasonette for an upcoming project. It looks really cool. It got pretty much all I need as far as I can tell. However, I am struggling to see how I can build a view that allows the user to add and manage tags (like attaching tags to a picture). Has anyone implemented something like this using Jasonette? Or should I use a web container with event set to default and just build it using html and js? Thanks!

**Comment by ghost** [comment]
might better to post this on http://forum.jasonette.com/

**Comment by Corstiaan84** [comment]
Done. Thanks.

**Comment by gliechtenstein** [comment]
Answered it over at the forum http://forum.jasonette.com/t/how-to-create-a-view-that-supports-tags/705/4?u=ethan
