### ISSUE TITLE
switch is somewhat broken in iOS

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#299]
the `switch` appears to remember its setting even when reloading a view:

https://jasonbase.com/things/Aq00

Note: the current version of Jason in the apple ios app store does not seem to have switches. I'm on `develop`.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/7a9f4f8de1a2d838b9f6312f83c92672f1b7c724

More demos: https://jasonbase.com/things/WxM2

**Comment by ghost** [comment]
any chance of getting a new iOS and Android Jason app out with these latest changes compiled in?  For playing with the new stuff which you're creating it would be great to have an up to date develop-based app in the store(s).

**Comment by cpg** [comment]
So, actually, I was hoping that changing the variable associated with the switch would change the appearance of it on the screen. Any chance that could be implemented?

At the moment, I hooked the `error` from an alert where the user cancels it to `$reload`, which causes a network request. Much less efficient than changing the value of the switch.
