### ISSUE TITLE
Invalid App Store Icon - ... Can't be transparent or contain an alpha channel

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#326]
this is new, the error didn't used to happen a few weeks back (with the exact same png for my icon) - I've even tried switching to a jpg instead but looks like the generate_icons script is generating invalid pngs, I can try a mogrify on them to remove the alpha channel if that's the problem, but didn't you also have this problem when you recently released the updated Jason app?

**Comment by ghost** [comment]
update: running 

```
mogrify -alpha off app/Jasonette/Media.xcassets/AppIcon.appiconset/*.png
```
resolves the problem.

**Comment by tumelogasetlolwe** [comment]
Jason or Jasonette?
Which one works best on app store
