### ISSUE TITLE
Vision example crashes Jason app

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#327]
the $vision example at http://docs.jasonette.com/actions/#visionscan

https://jasonbase.com/things/xDrM

Jason crashes shortly after starting the camera

iOS (latest) iPhone 7+

**Comment by gliechtenstein** [comment]
Thanks for reporting, i left out one important part:

the camera needs to be back-facing (the front-facing camera only can see your face and is not used for scanning barcodes), so you have to specify that in the markup.

Here's an example that works: https://jasonbase.com/things/q8xk/edit

I also updated the documentation to reflect this http://docs.jasonette.com/actions/#visionscan

**Comment by ghost** [comment]
thank you! we should add this to the jsonpedia, really appreciate the super fast response.
