### ISSUE TITLE
[Bug] Pull to refresh taking up space

### ISSUE THREAD

**Issue by jackchuka** [Jasonette/JASONETTE-iOS#33]
#### Problem: 
"Pull to refresh" taking up the top space and not fully going all the way back.
<img width="310" alt="screen shot 2016-11-10 at 4 39 27 pm" src="https://cloud.githubusercontent.com/assets/3062504/20200217/b87ca28e-a764-11e6-86aa-2082f9c3a3c9.png">

#### Video:
![ezgif-604325124](https://cloud.githubusercontent.com/assets/3062504/20200384/c48b7d38-a765-11e6-8b10-5d19b10d44d1.gif)

#### To replicate
1. Open Jasonette app with [Twitter Example](https://raw.githubusercontent.com/Jasonette/Twitter-UI-example/master/home.json). * Not this example specific.
2. Check "Pull to refresh" works properly.
3. Navigate to different tab from the footer.
4. Go back to Home tab.
5. Check "Pull to refresh" and see if it stays on top of the page.

**Comment by gliechtenstein** [comment]
I think it's fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/4e68dfe35bc348954d9ab45ed82201dcc69ba6ea

@jackchuka could you check? Thanks!

**Comment by gliechtenstein** [comment]
I've tried it on my devices and they're all fixed there, so assuming it's fixed. Please reopen if it's still problematic. Thanks!

**Comment by jackchuka** [comment]
Sorry it took awhile to get back.
Seems all good on master branch :)
Thanks!

**Comment by gliechtenstein** [comment]
I think you mean develop branch haha. Thanks for reporting! :)

**Comment by jackchuka** [comment]
Oops my bad 😆
