### ISSUE TITLE
url entity encoding problem

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#340]
query params in an $href like:
 
"href" {
    "url" : "http://example.com?q=Jiří Kovanda"
  }
gets encoded and sent as 

GET /?q=Ji%25C5%2599%25C3%25AD%20Kovanda HTTP/.....

should be entity encoded as:

q=Ji%C5%99%C3%AD%20Kovanda

Looks like Jasonette is double encoding the percent character. The characters before the ? need to be escaped, the characters after need to entity encoded.

**Comment by gliechtenstein** [comment]
Should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/eb29f78cd25de87657241aee845c7fc47e3cf2be on `develop`
