### ISSUE TITLE
Multiple empty spaces are added above the Tabs Footer on every reload (reproducible) 

### ISSUE THREAD

**Issue by kimheisler** [Jasonette/JASONETTE-iOS#342]
Hello,
as i mentioned in the forum:
[http://forum.jasonette.com/t/multiple-empty-spaces-are-added-above-the-footer-on-every-reload-reproducible/854](http://forum.jasonette.com/t/multiple-empty-spaces-are-added-above-the-footer-on-every-reload-reproducible/854)
i found the following bug when using the Tabs Footer:

I noticed when using the Tabs Footer on every reload an empty space with the height of the footer is added above the footer. This behavior is reproducible and it is even in the Twitter-UI-Demo.

As a demonstration i captured this video using the Twitter-UI-Demo:
[https://adobe.ly/2qVIqBu](https://adobe.ly/2qVIqBu)

I think in Xcode it has to do something with the lines around 1083 in the JasonViewController.m

```
CGFloat bottom_padding = 0.0;
  if (body[@"footer"] && body[@"footer"][@"tabs"]) {
      bottom_padding += self.tabBarController.tabBar.frame.size.height;
  }
  if (body[@"footer"] && body[@"footer"][@"input"]) {
      bottom_padding += self.composeBarView.frame.size.height;
  }
  self.tableView.contentInset = UIEdgeInsetsMake(self.tableView.contentInset.top, self.tableView.contentInset.left, self.tableView.contentInset.bottom+bottom_padding, self.tableView.contentInset.right);
original_bottom_inset = self.tableView.contentInset.bottom;
```

**Comment by gliechtenstein** [comment]
This bug should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/de863aa1227d6597d37ff9459f10c42816606441

Thanks for reporting! Please try it out and close the issue if you confirm that it's been fixed.

**Comment by kimheisler** [comment]
Thank you, it's working 👍
