### ISSUE TITLE
*push* transition showing search bar header from parent view

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#343]
Using

https://www.jasonbase.com/things/DG11.json

Iff you click through on a filtered item the search bar is visible over the new view 

see [here](https://forum.jasonette.com/uploads/default/original/1X/54d55b62ad59f15176608c9252e909789d421a1d.gif) for video

**Comment by gliechtenstein** [comment]
This should be fixed https://github.com/Jasonette/JASONETTE-iOS/commit/438c0b16140f3e25280e589930d9b5fb65802809 Please close if it did. Otherwise let me know
