### ISSUE TITLE
*modal* transition not repainting search bar header on parent view after close

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#344]
Using

https://www.jasonbase.com/things/DG11.json

After typing a search, clicking a link this time changing the above from push to modal transition, after closing modal the search bar header is not painted, once the search "clear" button is tapped. There is space for it, but it's not being painted. Sometimes you have to repeat the sequence, sometimes it happens first time.

latest iOS version

**Comment by gliechtenstein** [comment]
I didn't completely understand the situation from the explanation but maybe this fix took care of it? https://github.com/Jasonette/JASONETTE-iOS/commit/438c0b16140f3e25280e589930d9b5fb65802809 

If not, please let me know, another video would be helpful. Thanks

**Comment by ghost** [comment]
This one isn't fixed with the latest change.

Sorry I wasn't clear on the steps, this is how I reproduce it:

- open https://jasonbase.com/things/dmmb (that's the same as above except modal rather than push)
- type "sch" (or whatever)
- click one of the items (opens in modal)
- click close X (back to list view)
- click the search bar's "cancel" word

at that point the search bar disappears. It's possible that this was deliberate, but unless the other content slides up to replace it it looks weird - maybe though is this is intentional, could I change the bug to allow for a search bar option to disable "cancel" please?

**Comment by gliechtenstein** [comment]
What device and OS are you using? I tried it on all my devices and simulators and on all the devices the "cancel" button goes away immediately upon the modal transition, which means when we come back from the modal view, there is no "cancel" button to press.

And that was exactly the fix I made in the above commit so the "cancel" button shouldn't be there when you come back. Can you try cleaning the project and retry? And if it still happens, please share the OS and the device, and also a video would be helpful.
