### ISSUE TITLE
Add SMS action

### ISSUE THREAD

**Issue by realitix** [Jasonette/JASONETTE-iOS#349]
Hello,
Sadly I can't develop on android but can you add the send sms action like I did here: https://github.com/Jasonette/JASONETTE-Android/pull/240

Then we could add it to the doc.
This action allows to send a SMS and can be very useful.

**Comment by clsource** [comment]
I believe this can be achieved by using href

```
{
  "href" : {
    "url" : "sms://phone-number",
   "view": "app"
   }
}
```

But some tests must be made in order to try that.
Thanks for your contribution could be added as an external optional component.
