### ISSUE TITLE
Compile/Link time is abysmal

### ISSUE THREAD

**Issue by seletz** [Jasonette/JASONETTE-iOS#35]
I noticed that the edit/compile/test cycle when working on real devices is abysmally slow even on my maxed out MB Pro.

The build seems to use the most time in the "custom build scripts".

**Comment by seletz** [comment]
This seems to be cocoapods related.

I'm trying out the tips suggested here: https://tech.zalando.com/blog/speeding-up-xcode-builds/ and report back.

**Comment by seletz** [comment]
So w/o any changes I see 52.625s build time.

**Comment by gliechtenstein** [comment]
Relevant: https://github.com/CocoaPods/CocoaPods/issues/6118

I knew it! It's always XCode's fault

**Comment by gliechtenstein** [comment]
Can you try the solutions suggested here? http://stackoverflow.com/questions/40257968/slow-app-compilation-with-new-sierra-update/40298722#40298722

**Comment by seletz** [comment]
Well I don't have that many certs in my keychain, and no duplicates.

Will try the parallel code signing.

**Comment by seletz** [comment]
Ok, the parallel code signing in cocoapods 1.2.1.beta.1 works little wonders.  It's still slow all things considered, but it's no longer _dog slow_.

This worked for me:
https://stackoverflow.com/questions/40257968/slow-app-compilation-with-new-sierra-update/40353923#40353923

Relevant thread at cocoapods:
https://github.com/CocoaPods/CocoaPods/pull/6088#issuecomment-257441733

**Comment by gliechtenstein** [comment]
I couldn't get it to work :(

This is what my build settings looks like. And I also updated cocoapods to `--pre`. Does this about right?

![screen shot 2016-11-14 at 8 28 35 pm](https://cloud.githubusercontent.com/assets/16613330/20289651/096c194e-aaa9-11e6-8a25-49ea1e4f04c5.png)

**Comment by gliechtenstein** [comment]
Might this be why? : 

![screen shot 2016-11-14 at 8 40 46 pm](https://cloud.githubusercontent.com/assets/16613330/20289920/ae6366c2-aaaa-11e6-9b8a-c572ac1a5239.png)

If it's 2 cores, i don't think it will significantly make things faster...

**Comment by seletz** [comment]
Uhh, yes.  The proposed "solution" isn't really a solution -- it's just throwing more CPUs at the problem.  In your case, I agree that this doesn't really has a chance to help.  Sorry.
