### ISSUE TITLE
Development Moved to https://github.com/jasonelle/jasonelle

### ISSUE THREAD

**Issue by clsource** [Jasonette/JASONETTE-iOS#360]
https://github.com/jasonelle/jasonelle
will continue Jasonette legacy. Issues and pull request would be slowly tackled in the other repo

**Comment by kintaro1981** [comment]
I'm a little bit confused... what happened?

**Comment by kintaro1981** [comment]
oh I see now:
https://jasonelle.com/docs/history.html
