### ISSUE TITLE
back button is not working

### ISSUE THREAD

**Issue by vkprakash** [Jasonette/JASONETTE-iOS#361]
"header": {
	"menu": {

              "items": [{
    "type": "vertical",
    "components": [{
      "type": "button",
      "url": "https://.....",
      "action": { 
      	"type": "$back"
       } 
    }]
  }]
	}
}

This code isn't working. I got this directly from the jasonett website, does anyone know how to fix this?

**Comment by clsource** [comment]
hello, this is missing the basic structure.

```json
{
   "$jason": {

    }
}
```

please go to the docs in https://jasonelle.com/docs
for more info.
