### ISSUE TITLE
Links are not being decoded causing issues for links with # and other symbols  

### ISSUE THREAD

**Issue by sbashyal** [Jasonette/JASONETTE-iOS#38]
For example, this Jason will result in 404 for the linked page because # is not decoded on the webview  
{
      "type": "label",
      "text": "Visit Website",
      "href": {
                 "url": "http://simplydo.com/cryptography/#/about",
                "view": "Web"
                }
    }

**Comment by gliechtenstein** [comment]
Fixed this on https://github.com/Jasonette/JASONETTE-iOS/commit/c476aee9390e33a94dec832e33427ab7eb1c6d34 Please pull from dev and it should work.

Please reopen if this still doesn't work!

**Comment by gliechtenstein** [comment]
@sbashyal actually i should have confirmed it works before closing. Could you confirm it works when you get a chance @sbashyal ? Thanks!

**Comment by sbashyal** [comment]
@gliechtenstein It is working now. The issue has been resolved. Thanks much for quick fix.
