### ISSUE TITLE
Web view with reader mode

### ISSUE THREAD

**Issue by jereze** [Jasonette/JASONETTE-iOS#44]
Hi,

Feature idea.

When opening a web browser view (`"view":"web"`), an option to open Safari with the reader mode.
That's an [option given by SFSafariViewController](https://developer.apple.com/reference/safariservices/sfsafariviewcontroller/1621221-init).

**Comment by gliechtenstein** [comment]
Good idea!

In case anyone's looking to jump in and contribute, here's the part where it handles the SFSafariViewController launch https://github.com/Jasonette/JASONETTE-iOS/blob/develop/app/Jasonette/Jason.m#L1842

**Comment by clsource** [comment]
Implemented here as options

https://github.com/jasonelle/jasonette-ios/pull/1

```json
{
	"options": {
		"reader": true
	}
}
```
