### ISSUE TITLE
when using "replace" transition, the back button should not be shown

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#47]
at the moment it appears to be shown when using replace, so the user can go back to the previous view.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/526ddb63577e56f79bbeae2b47bbb38511824405 @cpg please try it out and see if it works!

**Comment by cpg** [comment]
It works well. Great job!
