### ISSUE TITLE
The header briefly displays its template expression before rendering (Example: {{$jason.foo}})

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#50]
with a templates.body.header.title = "{{$json.foo}}"

where foo is { "foo": "hello" } returned by the on load handler
 
while the data is still being fetched, the title shows as "{{$json.foo}}" then when loaded turns into "hello"

**Comment by gliechtenstein** [comment]
@darenr can you provide the full JSON or link to it?

**Comment by ghost** [comment]
{
  "$jason": {
    "head": {
      "style": {
        "background": "#000066"
      },
      "templates": {
        "body": {
          "style": {
            "background": "#000066"
          },
          "header": {
            "style": {
              "background": "#000066",
              "color": "#ffffff",
              "font": "HelveticaNeue-Bold"
            },
            "title": "{{$jason.title}}"
          },
          "sections": [
            {
              "items": 
                {
                  "{{#each $jason.artworks}}": {
                    "type": "label",
                    "text": "{{title}}",
                    "style": {
                      "size": "18",
                      "color": "#ffffff",
                      "font": "HelveticaNeue-Bold",
                      "padding": "10"
                    }
                  }
                }

```
        }
      ]
    }
  },
  "actions": {
    "$pull": {
      "type": "$reload"
    },
    "$load": {
      "type": "$network.request",
      "options": {
        "url": "https://www.jasonbase.com/things/5Wd.json"
      },
      "success": {
        "type": "$render"
      },
      "error": {
        "type": "$util.banner",
        "options": {
          "title": "Error",
          "description": "Something went wrong fetching even data"
        }
      }
    }
  }
}
```

  }
}

**Comment by gliechtenstein** [comment]
Hmm that's strange, I've just tried it and at least the current version I see seems to have no problem.

Also, unless you have something inside $jason.body, it's not supposed to render anything until you call `$render`. That's the whole reason why we have templates inside $jason.head, where it doesn't get displayed by default. Nothing inside $jason.head gets rendered. It is only when you call $render that it renders the template.

Can you share how to replicate this?

**Comment by ghost** [comment]
I'm using the develop branch, the only thing I do is start with this 

https://www.jasonbase.com/things/KWV.json 

and then click any of the "cards" and it will open

https://www.jasonbase.com/things/Qnn.json

and for a second or two - before it's loaded the data the title says "{{title}}"

does that reproduce for you? I'll hold off editing those json files for now while you try to reproduce it.

**Comment by gliechtenstein** [comment]
Aha I see it now. Just to confirm, you mean the header title says `{{$jason.title}}` for a brief second before switching out to the page title (such as "Frozen world of ..."), right?

**Comment by ghost** [comment]
exactly, glad you can see it too, it's probably me doing something wrong since I'm only several hours familiar with jasonette.

**Comment by gliechtenstein** [comment]
Nope! you've actually found a bug :) 

Just wrote up a minimal markup just to isolate this https://jasonbase.com/things/q10/edit and it still happens there too.

I'll label this as bug. Sorry about the confusion!

![header_bug](https://cloud.githubusercontent.com/assets/16613330/20367436/73628804-ac1d-11e6-982f-aede7ac58ec0.gif)

**Comment by ghost** [comment]
Thank you. - I'm curious how you recorded the screen like that, I looked into iPhone screen recorders and it seemed like a lot of work.

**Comment by gliechtenstein** [comment]
@darenr I use quicktime player to record it, it's actually simple once you get used to it. Just need to connect the phone and record.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/b1be0a33bb33ef578b587a8244ba58496c7366ad
