### ISSUE TITLE
Unknown property class

### ISSUE THREAD

**Issue by KarimJedda** [Jasonette/JASONETTE-iOS#52]
Thanks for the awesome tool, i'm still stuck at the demo though..

Any ideas where this could come from?

<img width="753" alt="bildschirmfoto 2016-11-16 um 23 43 00" src="https://cloud.githubusercontent.com/assets/5029053/20368918/840ff87e-ac56-11e6-920c-74b7fe7fbbbc.png">

Thanks!

**Comment by gliechtenstein** [comment]
Haha this is one of the FAQs that I made an entry just for this! Here you go: https://jasonette.github.io/documentation/#troubleshoot

Basically you need to update your XCode :)

Please try this and share if it worked!

**Comment by KarimJedda** [comment]
Thank you so much, I will try it during the day and keep you posted. 

I will keep in mind to read the FAQ (when i am fully awake) next time, I somehow missed it the first time ^^

**Comment by gliechtenstein** [comment]
@KarimJedda did it work? Feel free to close this if it did. Or if it didn't work let me know :)

**Comment by KarimJedda** [comment]
It worked! It's alive! Alriiiight! 👍  
Had to install macOS SIerra, update Xcode, Add a developper account, set up code signing and all the stuff but yeah! 
Thank you!
We're in business!
