### ISSUE TITLE
Causes crash on develop branch

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#56]
```
{
  "$jason": {
    "head": {
      "data": {
        "posts": [
          {
            "title": "title1"
          },
          {
            "title": "title2"
          }
        ]
      },
      "templates": {
        "sections": {
          "{{#each posts}}": [
            {
              "items": [
                {
                  "components": [
                    {
                      "type": "label",
                      "text": "{{title}}"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

should add: iPhone 7plus, IOS 10.1, "develop" branch

**Comment by gliechtenstein** [comment]
@darenr Two things: 
1. When using the `#each` command in a template, you need to have an object as its child, not an array. `#each` simply iterates through the item (`posts` in this case) with its child template and generates the resulting array.
2. templates must have a name. And the default template is `body`, which renders into `$jason.body` by default. You can decide to have [multiple templates](https://github.com/Jasonette/Jasonpedia/blob/gh-pages/core/render/templates.json) and render them by specifying the `template` option if you want to (but that's an edge case so you'll probably not need this). So in this case you simply need to wrap your template inside `body`.

So in this case, this should work:

``` json
{
  "$jason": {
    "head": {
      "data": {
        "posts": [
          {
            "title": "title1"
          },
          {
            "title": "title2"
          }
        ]
      },
      "templates": {
        "body": {
          "sections": {
            "{{#each posts}}": {
                "items": [
                  {
                    "components": [
                      {
                        "type": "label",
                        "text": "{{title}}"
                      }
                    ]
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}
```

p.s.

See https://github.com/Jasonette/Jasonpedia/tree/gh-pages/template for more examples on using templates.

**Comment by ghost** [comment]
thanks for the link and the example, but that didn't work either, it rendered two empty sections. Knowing that #each generates an array itself is helpful.

I'll play around with and go through the link examples and see if I can figure it out. The example I gave was actually stripped down and what I really want to do is next loops but I'll first get this simple one to work before tacking that.
