### ISSUE TITLE
images do not seem to trigger $href action when inside a layout

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#65]
Here is an example where putting some images in a layout makes them not clickable. I thought they were supposed to be https://jasonbase.com/things/R28

**Comment by cpg** [comment]
In case it was not clear, they work when they are items at the top level. Or when they are changed to buttons.

If this was on purpose, perhaps make a "url" option for buttons to display images in the middle of the button?

**Comment by cpg** [comment]
Here is another example: https://jasonbase.com/things/8kd
from the docs, with an action in an image not working after wrapping it in a simple layout.

When the action is attached to the components as a whole, it appears to work. This appears to be a work-around!

**Comment by gliechtenstein** [comment]
Resolved with https://github.com/Jasonette/JASONETTE-iOS/pull/94

Instead of attaching href or action to labels or images, the approach is to use image type buttons or label type buttons. buttons can have `action` attributes.

The syntax: https://github.com/Jasonette/documentation/issues/19
