### ISSUE TITLE
Strange bugs when using templates for segmented bar, it only display last header title

### ISSUE THREAD

**Issue by steve21124** [Jasonette/JASONETTE-iOS#68]
if using below json, segmented bar only display last one
![alt text](https://s15.postimg.org/ks3o8at17/Screen_Shot_2016_11_26_at_11_53_19_PM.png)

<PRE>
{
    "$jason": {
        "head": {
            "data": {
                "members": [
                            { "name": "Homer" },
                            { "name": "Marge" },
                            { "name": "Lisa" },
                            { "name": "Bart" },
                            { "name": "Maggie" }
                            ]
            },
            "templates": {
                "body": {
                    "nav": {
                        "style": {
                            "background": "#230B0F",
                            "font": "AvenirNext-Heavy",
                            "size": "14",
                            "color": "#ffffff"
                        },
                        "items": [
                                  {
                                    "type": "tabs",
                                    "style": {
                                        "background": "#230B0F",
                                        "color": "#ffffff",
                                        "tintColor": "#ffffff"
                                    },
                                  "items": {
                                        "{{#each members}}": {
                                            "text": "{{name}}",
                                            "url": "#"
                                        }
                                  },
                                  
                                  }
                            ]
                    }
                }
            }
        }
    }
}
</PRE>

but if use below json, it work fine
![alt text](https://s15.postimg.org/wt48d11tn/Screen_Shot_2016_11_26_at_11_59_03_PM.png)

<PRE>
{
    "$jason": {
        "head": {
            "data": {
                "members": [
                            { "name": "Homer" },
                            { "name": "Marge" },
                            { "name": "Lisa" },
                            { "name": "Bart" },
                            { "name": "Maggie" }
                            ]
            },
            "templates": {
                "body": {
                    "nav": {
                        "style": {
                            "background": "#230B0F",
                            "font": "AvenirNext-Heavy",
                            "size": "14",
                            "color": "#ffffff"
                        },
                        "items": [
                                  {
                                  "type": "tabs",
                                  "style": {
                                  "background": "#230B0F",
                                  "color": "#ffffff",
                                  "tintColor": "#ffffff"
                                  },
                                  "items": [
                                    {
                                        "text": "header1",
                                        "url": "#"
                                    },
                                            {
                                            "text": "header1",
                                            "url": "#"
                                            },
                                            {
                                            "text": "header1",
                                            "url": "#"
                                            },
                                            {
                                            "text": "header1",
                                            "url": "#"
                                            }
                                  ]
                                  ,
                                  
                                  }
                                  ]
                    }
                }
            }
        }
    }
}
</PRE>

**Comment by gliechtenstein** [comment]
@steve21124 wow how did you come up with this code? I don't think this is even documented! I am asking because if you found this somewhere, I need to make sure I correct it.

First of all, the tab feature is not officially supported. It used to exist but I took it out before launching because of some syntax confusion it caused. If you want to use a tabbed structure, I recommend you use the [footer.tabs](https://jasonette.github.io/documentation/document/#tabs) for now.

Secondly, `nav` was deprecated in favor of [header](https://jasonette.github.io/documentation/document/#bodyheader). Please check out the syntax there.

The reason why it partially works is because I kept some of the code in there, but it's not for use. Sorry for the confusion! And please let me know how you found that code sample so I can do something about it :)

**Comment by steve21124** [comment]
good to know and yes, itis undocumented as I try some layout feature. I think i got it from https://jasonette.github.io/documentation/examples/#kitty

**Comment by gliechtenstein** [comment]
aha! nice catch! Sorry for the confusion. I'll fix all the samples on that page.

**Comment by steve21124** [comment]
no problem and no hurry as there other other higher priority one.. no confusion. just testing out some of the features :)
