### ISSUE TITLE
Question: How to handle 3 view controller based on one json?

### ISSUE THREAD

**Issue by steve21124** [Jasonette/JASONETTE-iOS#72]
Assuming the app has rows of countries, and for each countries, it has states and each states has cities. 
First View controller has rows of countries and on tap, it will push second view controller contain states of the specific country and on tap, it will push a third view controller contains rows of cities for that states. 

do you think it is possible to achieve it? This way, I don't need to create lots of json file for each of the screen. only need one and all of the view controller refer to that one json data.

I think the only thing I need is to have the second and third view controller refer to the first json and filter it accordingly
 <PRE>
===== json data ========
Screen1
   Screen1Row1
   		Screen2Row1
			Screen3Row1
			Screen3Row2
			Screen3Row3						
   		Screen2Row2
   		Screen2Row3				
   Screen1Row2
   Screen1Row3
   Screen1Row4
   </PRE>

**Comment by gliechtenstein** [comment]
Are you talking about how to share the same dataset for multiple views?

If that's the case, you can have 3 separate views each with its own template, and then fetch from the same JSON data endpoint using `$network.request`, finally to `$render` using the 3 different templates.

For example, if you had a data endpoint at https://jasonbase.com/things/WDx that looks like this:

```
{
  "drinks": [
    {
      "name": "coffee",
      "caffeine": "yes",
      "sugar": "no",
      "color": "black"
    },
    {
      "name": "coke",
      "caffeine": "yes",
      "sugar": "yes",
      "color": "black"
    },
    {
      "name": "sparkling water",
      "caffeine": "no",
      "sugar": "no",
      "color": "transparent"
    },
    {
      "name": "mountain dew",
      "caffeine": "yes",
      "sugar": "yes",
      "color": "yellowgreen"
    }
  ]
}
```

In one template you could do something like:

```
{
  "$jason": {
    "head": {
      "title": "sugar free drinks",
      "templates": {
        "body": {
          "sections": [{
            "items": {
              "{{#each $jason.drinks.filter(function(item){ return item.sugar=='no';}) }}": {
                "type": "label",
                "text": "{{name}}"
              }
           }]
        }
      },
      "actions": {
        "$load": {
          "type": "$network.request",
          "options": {
            "url": "https://jasonbase.com/things/WDx"
          },
          "success": {
            "type": "$render"
          }
        }
      }
    }
  }
}
```


And in another you could do:

```
{
  "$jason": {
    "head": {
      "title": "black drinks",
      "templates": {
        "body": {
          "sections": [{
            "items": {
              "{{#each $jason.drinks.filter(function(item){ return item.color=='black';}) }}": {
                "type": "label",
                "text": "{{name}}"
              }
           }]
        }
      },
      "actions": {
        "$load": {
          "type": "$network.request",
          "options": {
            "url": "https://jasonbase.com/things/WDx"
          },
          "success": {
            "type": "$render"
          }
        }
      }
    }
  }
}
```

Notice how both views are hitting the same URL that returns the first json.

Anyway, technically this is all possible, but if I had to recommend, I would recommend doing all this filtering logic in the backend. That way, the frontend just needs to render what the backend returns, and you don't even need to do all this templating stuff on the frontend. That would make things much simpler.

Please let me know if I misunderstood your question.

**Comment by steve21124** [comment]
Thanks for the json. Now, I know what I need to do. seems like I need 3 jsons files for countries and states and cities. 
https://jasonbase.com/things/countries
https://jasonbase.com/things/states?countryId={{drinkId}}
https://jasonbase.com/things/cities?stateId={{stateId}}

<PRE>
{
  "$jason": {
    "head": {
      "title": "black drinks",
      "templates": {
        "body": {
          "sections": [{
            "items": {
              "{{#each $jason.drinks.filter(function(item){ return item.color=='black';}) }}": {
                "type": "label",
                "text": "{{name}}",
				"href": {
				     "url": "https://jasonbase.com/things/states?countryId={{drinkId}}"
				 }
              }
           }]
        }
      },
      "actions": {
        "$load": {
          "type": "$network.request",
          "options": {
            "url": "https://jasonbase.com/things/WDx"
          },
          "success": {
            "type": "$render"
          }
        }
      }
    }
  }
}
</PRE>

and as you said, can do the filtering from backend custom json action
https://jasonbase.com/things/countries  => retrieve all countries
https://jasonbase.com/things/countries?type=states&countryid={{countryid}} retrieve all states
https://jasonbase.com/things/countries?type=cities&stateid={{stateid}} retrieve all cities
