### ISSUE TITLE
feature request: admob

### ISSUE THREAD

**Issue by birdchan** [Jasonette/JASONETTE-iOS#79]
Add admob support, or other types of ads.

**Comment by wajahatch888** [comment]
+1

**Comment by lukeramsden** [comment]
+1

**Comment by jkkorn** [comment]
+1

**Comment by wajahatch888** [comment]
[Pull Request](https://github.com/Jasonette/JASONETTE-iOS/pull/92)  :)

**Comment by gliechtenstein** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

Thanks to @wajahatch888 we now have Ad support on iOS Jasonette! Just like the rest of Jasonette, you can add/remove AdMob ads simply by specifying them in the JSON markup. More on the syntax below, but first, here's an adhoc "howto" instruction (Official documentation coming soon):

One thing to keep in mind: Ads are not enabled by default, so you must enable them. To enable, follow the following steps:

1. Download the latest version of Jasonette from develop branch and unzip: https://github.com/Jasonette/JASONETTE-iOS/archive/develop.zip
2. Download CocoaPods app from here: https://cocoapods.org/app 
3. Run CocoaPods app. From the app menu, open `File > Open Podfile`. Then find the project folder you just unzipped. From the project folder, go into `app` folder and you should see a file called `Podfile`. Select that file and open it from CocoaPods app. You should see this screen:

![screen shot 2016-12-28 at 7 12 59 am](https://cloud.githubusercontent.com/assets/16613330/21521669/21a9f0b2-cccd-11e6-87e1-a41fe8c35da7.png)

4. Uncomment the `pod 'GoogleMobileAds', '~> 7.8'` line (By removing the # character) and press the `install` button at the top right corner. The install will start. After that you'll see the following screen:

![screen shot 2016-12-28 at 6 45 36 am](https://cloud.githubusercontent.com/assets/16613330/21521338/100000d4-ccca-11e6-9dfa-d4cbd4ad5ada.png)

Notice the green `Installing GoogleMobileAds` line from above screenshot. That means the library has been successfully installed into the project and you can use it.

5. Now from Finder, go to your project root folder and run `Setup` and walk through the setup process just like any other Jasonette project.

6. One last thing, you need to turn on the Ad feature from the code as well. To do this, open `Jasonette > Config > Constants.h` file from XCode, Uncomment the line: `#define ADS 1` (by removing the `//`). The result should look something like this:

![screen shot 2016-12-28 at 6 54 53 am](https://cloud.githubusercontent.com/assets/16613330/21521411/ab366c6e-ccca-11e6-908b-b78399ddc1a5.png)

And that's it! You're good to go. You can now summon ads by using the following syntax:

```json
{
 "$jason": {
   "body": {
     ..
     "ads": [{
       "type": "admob",
       "options": {
         "type": "banner",
         "unitId": "a14dccd0fb24d45"
       }
     }, {
       "type": "admob",
       "options": {
         "type": "interstial",
         "unitId": "ca-app-pub-6606303247985815/7014816684"
       }
     }]
   }
 }
} 
```

Check out this Github issue thread to learn more https://github.com/Jasonette/JASONETTE-iOS/pull/92#issuecomment-269276568

@wajahatch888 please correct me if I got anything wrong.

🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by wajahatch888** [comment]
@gliechtenstein , You have covered each and every point in detail. 👍

**Comment by lukeramsden** [comment]
I'll do some work of the documentation when I get home 🎉🎉🎉

**Comment by wajahatch888** [comment]
@lukeramsden , That would be Awsome 👍

**Comment by birdchan** [comment]
thanks @wajahatch888 and @gliechtenstein for the hard work, I can keep my apps free now. =)

**Comment by gliechtenstein** [comment]
@birdchan please try out and let us know if things don't work as expected! 🎉

**Comment by lukeramsden** [comment]
@gliechtenstein @wajahatch888 Alright, I'm working on the docs. So, theres 2 types of ads, right? `banner` and `interstial` (spelled wrong, its interstitial).  And how does the unitID format work? I'm not familiar with admob, is there more than one format for unitID (or can they put whatever they want in it and it just gets sent regardless)?

**Comment by lukeramsden** [comment]
After looking at the code, there is a `footer` ad aswell, does that use any more specific options? Does it have to go inside a specific view?

**Comment by lukeramsden** [comment]
Do you think you could come up with an example app for me to see how it should look?

**Comment by lukeramsden** [comment]
After some testing, I can't get it to work. Do you think you could send me a screenshot of it in action for the docs?

**Comment by wajahatch888** [comment]
@lukeramsden , When you create Admob ad (Banner/ interstitial) on [https://apps.admob.com/](https://apps.admob.com/) they give you `unitId` e.g `ca-app-pub-6606303247985815/7014816684`. This `unitId` is `string` type.
`footer` ad is actually `banner`. It always shows on bottom of screen. If json has `body.footer` then `banner` ad will appear above `footer`.
Have you followed all the steps which @gliechtenstein mentioned above? or do you need json url to make it work?

**Comment by wajahatch888** [comment]
@lukeramsden , You can use following json to show ad in your app after doing above steps.
[https://jasonbase.com/things/BmP](https://jasonbase.com/things/BmP).

# **Screenshots**

### **Banner Ad**
![bannerad](https://cloud.githubusercontent.com/assets/5916442/21547493/3c6e0816-ce08-11e6-8fb5-72e9beca42a5.png)

### **Interstitial Ad**
![interstitialad](https://cloud.githubusercontent.com/assets/5916442/21547511/5b9c3172-ce08-11e6-845d-e277e9b2154a.png)

**Comment by gliechtenstein** [comment]
@lukeramsden if you ever get it to work, please let us know!
