### ISSUE TITLE
Is this production ready? Performance?

### ISSUE THREAD

**Issue by IvRRimum** [Jasonette/JASONETTE-iOS#8]
Hello,

I am looking at this and i must say, i am pretty impressed.

My questions(a lot of people could have the same questions):
Is this production ready? Can you actually make an entire app on jasonette?
If i am creating a large application, wont the performance hurt?

Thanks!

**Comment by gliechtenstein** [comment]
Yup I have several production apps on the Appstore. Try out this app : www.textethan.com
Jasonette engine was extracted out from Ethan app, and currently Ethan runs on an early version of Jasonette. 

But I think the best way is to just try out building some small apps, and you'll soon see how it works. Once you get used to the syntax you can literally build apps in like 10 minutes (which you would have taken days to build).

Also please join the Slack channel if you get stuck and have questions :)

**Comment by IvRRimum** [comment]
I am planing to create Homeless? clone(but with different story) using Jasonette-IOS for a test run. I think it would test out the most used stuff in app development.
The goal is to do it over next weekend.

I will make it open-source, so other's can see the strengths and minuses of Jasonette.

Thanks!
