### ISSUE TITLE
Loading authenticated Images

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-iOS#86]
For most cases we can simply fill out an image component with:

```
{
  "type": "image",
  "url": "<A_PUBLIC_IMAGE_URL>"
}
```

However, sometimes the image assets are protected and require authenticated requests. I made a branch to make this work, which adds a new attribute 'header' for image components, which will attach the header when making a request to the image asset:
```
{
  "type": "image",
  "url": "<A_PROTECTED_IMAGE_URL>",
  "header": {
    "Authorization": "Basic dne9ns0dlanengensDEhd="
  }
}
```

I tried to make it consistent with rest of the syntax but if anyone has a better idea on how to represent this in JSON, please feel free to share ideas. Here's the branch: https://github.com/Jasonette/JASONETTE-iOS/tree/authenticated_image

**Comment by gtramontina** [comment]
For basic auth, I believe that providing the credentials via the URL should be enough: "https://username:password@protected.com/image.jpg"

Now, being able to provide extra headers when needed is a great feature anyway. This gives us better control over how we communicate back to our servers.

**Comment by gliechtenstein** [comment]
Resolved with https://github.com/Jasonette/JASONETTE-iOS/commit/9010fcdb8979b1ea3bf44316091fd3152abc785e

1. This works for both image components and (image type) button components using the newly introduced `header` attribute.
2. Also it automatically attaches the `header` from session in case there's an existing session with the domain.

Here's the syntax:

- Image component
```json
{
  "type": "image",
  "url": "<A_PROTECTED_IMAGE_URL>",
  "header": {
    "Authorization": "Basic dne9ns0dlanengensDEhd="
  }
}
```

- image type button component
```json
{
  "type": "button",
  "url": "<A_PROTECTED_IMAGE_URL>",
  "header": {
    "Authorization": "Basic dne9ns0dlanengensDEhd="
  }
}
```
