### ISSUE TITLE
Custom Settings.plist for each target

### ISSUE THREAD

**Issue by golopupinsky** [Jasonette/JASONETTE-iOS#89]
Hi.
I'd like to have a different settings.plist file for every target I create in project for obvious reasons (each target should point to different url which is only configured in settings.plist). So, I was wondering if this could be supported? 
Another way to solve this is to completely get rid of settings.plist file and move its contents as an entry in info.plist, since every target will have its own info.plist.

**Comment by gliechtenstein** [comment]
Resolved with https://github.com/Jasonette/JASONETTE-iOS/pull/99
