### ISSUE TITLE
Would you consider making an Android version?

### ISSUE THREAD

**Issue by awnumar** [Jasonette/JASONETTE-iOS#9]
This is really quite a brilliant idea and well executed. Would you ever consider doing the same for android?

**Comment by gliechtenstein** [comment]
I think the most important piece of technology is the underlying grammar, and even this repo is just its iOS implementation. So YES.

**Comment by awnumar** [comment]
That's brilliant. I'll be keeping an eye on this project.

**Comment by dalerka** [comment]
Just dropped by to say thank you Ethan! Both the idea and your work are awesome!

**Comment by jossiwolf** [comment]
@gliechtenstein I'd be interested to contribute to the android version, any way I can?

**Comment by gliechtenstein** [comment]
Guys, as promised, I'm ready to show something, and sharing here first. Ping me on Slack if you have Android!

**Comment by gliechtenstein** [comment]
For got to close this. Here's the Android version! https://github.com/Jasonette/JASONETTE-Android
