### ISSUE TITLE
the search box appears to not invoke the $href action

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#91]
other actions appear to work (e.g. `$network.rquest`), but when using `$href`, there is no network request seemingly issued.

the intention was to be able to pass the search query to a call that then returns a whole new view with the search results. kind of like the gmail app.

this appears to not be possible from the search box.

**Comment by gliechtenstein** [comment]
fixed https://github.com/Jasonette/JASONETTE-iOS/commit/4f3e192cd5ff2980411f0394d0277811f7100090
