### ISSUE TITLE
Nav bar could not be hidden

### ISSUE THREAD

**Issue by golopupinsky** [Jasonette/JASONETTE-iOS#93]
Setting "hide" property on the header's style doesn't do anything. 
The `[navigationController setNavigationBarHidden:YES]` gets called but nothing changes, nav bar remains visible.

**Comment by wajahatch888** [comment]
@golopupinsky , Can you please provide json url so that we can debug?

**Comment by wajahatch888** [comment]
Issue fixed. [Pull Request](https://github.com/Jasonette/JASONETTE-iOS/pull/95)
