### ISSUE TITLE
Admob interstitial ad spelt wrong

### ISSUE THREAD

**Issue by lukeramsden** [Jasonette/JASONETTE-iOS#97]
Currently spelt interestial, should be interstitial.

**Comment by wajahatch888** [comment]
ahhh, Typo erro :/

**Comment by wajahatch888** [comment]
Just fixed it. [PR](https://github.com/Jasonette/JASONETTE-iOS/pull/98)

**Comment by gliechtenstein** [comment]
totally missed this too! just merged.
